services:
    lmsbooks_1:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: books1_in_lms_network
        ports:
            - "8087:8080"
        environment:
            SPRING_PROFILES_ACTIVE: instance1,bootstrap
        networks:
            - lms_network
        volumes:
            - "uploaded_files_volume_1:/tmp"

    lmsbooks_2:
        build:
            context: ..
            dockerfile: Dockerfile
        container_name: books2_in_lms_network
        ports:
            - "8088:8080"
        environment:
            SPRING_PROFILES_ACTIVE: instance2,bootstrap
        networks:
            - lms_network
        volumes:
            - "uploaded_files_volume_2:/tmp"

networks:
    lms_network:
        external: true

volumes:
    uploaded_files_volume_1:
    uploaded_files_volume_2:
